spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/eshop-basket
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update
      show-sql: false
      open-in-view: false
  resilience4j:
    circuitbreaker:
      instances:
        catalogService:
          minimumNumberOfCalls: 10
          registerHealthIndicator: true
          slidingWindowSize: 10
          permittedNumberOfCallsInHalfOpenState: 3
          waitDurationInOpenState: 10000
          failureRateThreshold: 50
rabbitmq:
  host: localhost
  port: 5672
